### ISSUE TITLE
creating and using functional components

### ISSUE THREAD

**Issue by ambrose-kibet** [ambrose-kibet/Math-Magicians#4]
I used functional components in my project .
To create functional components in react:
`function MyComponent () {
  return  <button>click me  </button>;
     }
export default Botton;
`
or `const MyComponent=()=><button>click me  </button>;
export default MyComponent
`

**Comment by codepantha** [comment]
# STATUS: APPROVED 🟢 ✔️ 

## Hi @ambrose-kibet 👋, 

Your project is complete!  There is nothing else to say other than... it's time to move on to the next milestone :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/2RGhmKXcl0ViM/giphy.gif"/>

## Highlights 🎯 
✔️ Used functional components instead of class-based ones 📌 
✔️ Calculator app working exactly as expected 📌

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
